### PR TITLE
Publish new goo version

### PR DESCRIPTION
**Pull request by janua**
@rich-nguyen

### CODE REVIEW

**Comment by rich-nguyen** [comment]
there's a lot files here....

**Comment by janua** [comment]
@rich-nguyen The update script must not have been run in awhile...!

**Comment by rrees** [comment]
@janua I want to stop publishing artifacts here. Would it possible to publish your library on Bintray or Maven Central?

**Comment by janua** [comment]
@rrees We are now looking into publishing this to bintray instead of here.

**Comment by rich-nguyen** [comment]
closing in favour of bintray https://github.com/guardian/platform/pull/896

**Pull request closed without merging**
